[package]
name = "humility-cmd-rng"
version = "0.1.0"
edition = "2021"
description = "Get entropy from Rng."

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
base64 = "0.13"
clap = { version = "3.0", features = ["derive", "env"] }
hif = { git = "https://github.com/oxidecomputer/hif" }
humility = { path = "../../humility-core", package = "humility-core" }
humility-cmd = { path = "../../humility-cmd" }
parse_int = "0.4"
